app_polls/urls.py
#!-*-coding:utf-8-*-
# !@Date: 2018/9/9 22:00
# !@Author: Liu Rui
# !@github: bigfoolliu


# 自建的urls.py文件,可以在项目中的urls.py指向此处
# from django.conf.urls import url
# from . import views

# from django.contrib import admin
from django.urls import path, re_path
from app_polls.views import *
# 使用URLconf的命名空间,便于区分多个app之间的URL name
from django.conf.urls import url


# 增加该变量,以后不同app之间的模板url name引用将更加清晰
app_name = 'app_polls'

urlpatterns = [
	# path('index/', index, name='index'),
	# re_path(r'^$', index, name='index'),
	# re_path(r'^(?P<question_id>[0-9]+)/$', detail, name='detail'),
	# re_path(r'^(?P<question_id>[0-9]+)/results/$', results, name='results'),
	# re_path(r'^(?P<question_id>[0-9]+)/vote/$', vote, name='vote'),

	# 为了使用类视图,修改URLConf重新设置
	re_path(r'^$', IndexView.as_view(), name='index'),
	re_path(r'^(?P<pk>[0-9]+)/$', DetailView.as_view(), name='detail'),
	re_path(r'^(?P<pk>[0-9]+)/results/$', ResultsView.as_view(), name='results'),
	re_path(r'^(?P<question_id>[0-9]+)/vote/$', vote, name='vote'),
]

app_polls/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta


# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)  # 问题文本
	pub_date = models.DateTimeField('date published')  # 发布日期

	def was_published_recently(self):
		"""判断是够最近发布到的"""
		now = timezone.now()
		# return self.pub_date >= timezone.now() - timedelta(days=1)
		return now - timedelta(days=1) <= self.pub_date <= now
	# 修改样式
	was_published_recently.admin_order_field = 'pub_date'
	was_published_recently.boolean = True
	was_published_recently.short_description = 'Published recently'

	def __str__(self):
		return self.question_text


class Choice(models.Model):
	# 外键的定义需要写在"多"的一方
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

app_polls/views.py
from django.shortcuts import render, get_object_or_404
# 导入响应模块
from django.http import HttpResponse, Http404, HttpResponseRedirect
# 导入模型
from .models import *
# 为了使用模板,需要导入
# from django.template import loader

from django.urls import reverse

# 为了类视图的需要导入
from django.views import generic


# Create your views here.
# def index(request):
# 	"""第一个视图"""
# 	# # 将最近的5个问题按照倒序输出
# 	# latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	# # 注意是将文本交给浏览器解析换行要根据html的规则
# 	# output = '<br>'.join([q.question_text for q in latest_question_list])
# 	# # print(output)
# 	# return HttpResponse(output)
#
# 	# 上面属于硬编码,下方为利用模板
# 	latest_question_list = Question.objects.order_by('-pub_date')[:5]
# 	# 指定使用的模板
# 	# template = loader.get_template('app_polls/index.html')
# 	# 指定模板中需要替换的内容
# 	context = {
# 		'latest_question_list': latest_question_list,
# 	}
# 	# return HttpResponse(template.render(context, request))
# 	# 加载模板,传递参数,返回HttpResponse对象非常常用,使用render函数直接替换上句以及template定义语句
# 	return render(request, 'app_polls/index.html', context)
#
#
# def detail(request, question_id):
# 	"""问卷的具体内容"""
# 	try:
# 		question = Question.objects.get(pk=question_id)
# 	except Question.DoesNotExist:
# 		raise Http404("Question does not exist.")
# 	# return HttpResponse("You're looking at question %s." % question_id)
# 	# 新写法
# 	context = {'question': question}
# 	return render(request, 'app_polls/detail.html', context)
#
#
# def results(request, question_id):
# 	"""问卷的结果显示页面"""
# 	# response = "You're looking at the results of question %s."
# 	# return HttpResponse(response % question_id)
#
# 	question = get_object_or_404(Question, pk=question_id)
# 	return render(request, 'app_polls/results.html', {'question': question})


# 将上面的视图函数全部更改为类视图
class IndexView(generic.ListView):
	"""index.html的类视图
	继承类视图ListView,表示显示一个对象的列表"""
	template_name = 'app_polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""返回最近发布的5个问卷"""
		return Question.objects.order_by('-pub_date')[:5]


# DetailView类视图需要从url中捕获称为pk的主键值,因此将url中的<question_id>修改成了<pk>
class DetailView(generic.DetailView):
	"""detail.html的类视图
	继承DetailView表示显示特定类型对象得详细页面"""
	model = Question
	template_name = 'app_polls/detail.html'


class ResultsView(generic.DetailView):
	"""results.html的类视图"""
	model = Question
	template_name = 'app_polls/results.html'


def vote(request, question_id):
	"""投票处理"""
	# 此句为try...except未找到对象产生404error语句的缩写
	question = get_object_or_404(Question, pk=question_id)
	try:
		# request.POST是一个类似字典的对象，允许你通过键名访问提交的数据.
		# request.POST[’choice’]返回被选择选项的ID，并且值的类型永远是string字符串.
		# 为防止因为post里没有choice键值产生KeyError异常,加None解决,即改为request.POST['choice', None]
		selected_choice = question.choice_set.get(pk=request.POST['choice'])

		print(type(selected_choice), selected_choice)  # models中定义的模型(类)
	except (KeyError, Choice.DoesNotExist):
		# 发生choice未找到的异常时,重新返回表单页面,并给出提示
		return render(request, 'app_polls/detail.html', {
			'question': question,
			'error_message': 'You did not select a choice.',
		})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		# 成功处理数据后,自动跳转至结果页面,防止用户多次连续提交
		# 在选择计数器加一后，返回的是一个HttpResponseRedirect而不是先前我们常用的HttpResponse。
		# HttpResponseRedirect需要一个参数：重定向的URL,对于所有的web开发,最好都要保持这种方式
		return HttpResponseRedirect(reverse('app_polls:results', args=(question.id,)))
		# return HttpResponse("You're voting on question %s." % question_id)

app_polls/templates/app_polls/detail.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<style type="text/css">
		#submit_btn{
			width: 100px;
			height: 50px;
			margin-top: 50px;
			margin-left: 50px;
		}
	</style>

	<body>
        <a href="/app_polls">回到主页面</a>
		<!--为了接收用户的投票选择,需要选择一个表单-->
        <h1>detail页面</h1>
		<h2>Question:{{question.question_text}}</h2>

		<!--出错显示消息-->
		{% if error_message %}
		<p><strong>{{error_message}}</strong></p>
		{% endif %}

		<!--显示一系列的单选按钮,按钮的值是选项的id,按钮的名字是字符串"choice"-->
		<!--当按了某个按钮并提交表单,一个包含数据choice=#的post请求将被发送给指定的url-->
		<form action="{% url 'app_polls:vote' question.id %}" method="post">
			<!--post请求需要考虑跨站请求伪造的安全问题,即csrf-->
			<!--django使用csrf_token标签,表示签名不可改,固定格式,位置任意,只要在form表单内-->
			{% csrf_token %} {% for choice in question.choice_set.all %}
			<!--forloop.counter是django系统专门提供的一个变量,用来表示当前循环的次数,用来给虚幻项目添加有序数标-->
			<input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}" />
			<label for="choice{{forloop.counter}}">{{choice.choice_text}}</label><br /> {% endfor %}

			<input type="submit" value="Vote" id="submit_btn"/>
		</form>
	</body>

</html>

app_polls/templates/app_polls/index.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title></title>
		
		<!--% static %模板标签会生成静态文件的绝对URL路径-->
		{% load static %}
		<!--注意css样式引用的目录,static实际上就是已经相当于声明了之前的多级目录,后面直接就是app下的static目录-->
		<link rel="stylesheet" type="text/css" href="{% static 'app_polls/style.css' %}"/>
	</head>

	<body>
        <h1>index页面</h1>
        <h2>问题如下:</h2>
		{% if latest_question_list %}
		<ul>
			{% for question in latest_question_list %}
			<li>
                <label>{{ question.id }}:</label>
				<a href="{% url 'app_polls:detail' question.id %}">{{question.question_text}}</a>
			</li>
        	{% endfor %}
		</ul>
		{% else %}
		<p>No polls are available.</p>

		{% endif %}
	</body>

</html>

app_polls/templates/app_polls/results.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
	</head>
	<body>
        <a href="/app_polls/">回到主页面</a>
        <h1>results页面</h1>
		<h2>{{question.question_text}}</h2>
		<ul>
			{% for choice in question.choice_set.all %}
			
			<li>{{choice.choice_text}}--{{choice.votes}}vote{{choice.votes|pluralize}}</li>
			
			{% endfor %}
		</ul>
		<a href="{% url 'app_polls:detail' question.id %}">Vote again?</a>
	</body>
</html>